const char* sl__error_page_src = "<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title><%= $err.class.to_s %> at <%= Request.uri %></title>\n"
"    <style>\n"
"    body {\n"
"        font-family:Verdana, sans-serif;\n"
"        margin:0;\n"
"        font-size:13px;\n"
"    }\n"
"    .container {\n"
"        margin:0px auto;\n"
"    }\n"
"    header, section {\n"
"        display:block;\n"
"        padding:32px 64px;\n"
"        margin:0;\n"
"    }\n"
"    header {\n"
"        background-color:#f9d4cf;\n"
"        border-bottom:1px solid #ea6756;\n"
"    }\n"
"    h2 {\n"
"        font-weight:normal;\n"
"        margin:0;\n"
"        margin-bottom:16px;\n"
"    }\n"
"    h2 span {\n"
"        color:#666666;\n"
"    }\n"
"    header table {\n"
"        border-collapse:collapse;\n"
"    }\n"
"    header table th {\n"
"        text-align:right;\n"
"        font-weight:bold;\n"
"        padding-right:12px;\n"
"    }\n"
"    header table th, header table td {\n"
"        padding:4px 6px;\n"
"    }\n"
"    .backtrace {\n"
"        background-color:#f0f0f0;\n"
"        border-bottom:1px solid #999999;\n"
"    }\n"
"    code {\n"
"        background-color:#f0f0f0;\n"
"        padding:2px 4px;\n"
"        border:1px solid #d0d0d0;\n"
"    }\n"
"    strong {\n"
"        font-size:12px;\n"
"    }\n"
"    li {\n"
"        margin-bottom:12px;\n"
"    }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <header>\n"
"        <h2><%= $err.class.to_s %> <span>at <%= Request.uri %></span></h2>\n"
"        <table>\n"
"            <tr>\n"
"                <th>Message</th>\n"
"                <td><%= $err.message %></td>\n"
"            </tr>\n"
"            <% if $err.backtrace.any { %>\n"
"                <tr>\n"
"                    <th>File</th>\n"
"                    <td><%= $err.backtrace[0].file %></td>\n"
"                </tr>\n"
"                <tr>\n"
"                    <th>Line</th>\n"
"                    <td><%= $err.backtrace[0].line %></td>\n"
"                </tr>\n"
"            <% } %>\n"
"        </table>\n"
"    </header>\n"
"    <section class=\"backtrace\">\n"
"        <h2>Backtrace</h2>\n"
"        <ul>\n"
"            <% for frame in $err.backtrace { %>\n"
"                <li>\n"
"                    <% if Object == frame.receiver { %>\n"
"                        <code>#<%= frame.method %></code>\n"
"                    <% } elsif frame.receiver.is_a(Class) { %>\n"
"                        <code><%= frame.receiver %>.<%= frame.method %></code>\n"
"                    <% } else { %>\n"
"                        <code><%= frame.receiver.class %>#<%= frame.method %></code>\n"
"                    <% } %>\n"
"                    in <strong><%= frame.file %></strong>, line <strong><%= frame.line %></strong>\n"
"                </li>\n"
"            <% } %>\n"
"        </ul>\n"
"    </section>\n"
"    <section class=\"info\">\n"
"        <p>\n"
"            You are seeing this page because Slash is set to show descriptive error pages whenever an exception is not caught.\n"
"        </p>\n"
"        <p>\n"
"            To disable descriptive error pages, set <code>Response.descriptive_error_pages</code> to <code>false</code>\n"
"        </p>\n"
"    </section>\n"
"</body>\n"
"</html>\n"
;
