language: c
before_script:
  - sudo apt-get install libgmp-dev libmysqlclient-dev libgcrypt-dev libmarkdown2-dev
script: scripts/ci
notifications:
  irc:
    channels:
      - "irc.freenode.net#slash-lang"
