<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>sl</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(?x)
        (&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
        |&lt;!--(?!.*--&gt;)
        |\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
        )</string>
    <key>foldingStopMarker</key>
    <string>(?x)
        (&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
        |^\s*--&gt;
        |(^|\s)\}
        )</string>
    <key>name</key>
    <string>Slash</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>begin</key>
            <string>&lt;%+#</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.slash</string>
                </dict>
            </dict>
            <key>end</key>
            <string>%&gt;</string>
            <key>name</key>
            <string>comment.block.slash</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>&lt;%!!</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>invalid</string>
                </dict>
            </dict>
            <key>end</key>
            <string>%&gt;</string>
            <key>name</key>
            <string>source.slash.raw-echo.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#slash-language</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>&lt;%(?!&gt;!)=?</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.embedded.slash</string>
                </dict>
            </dict>
            <key>end</key>
            <string>%&gt;</string>
            <key>name</key>
            <string>source.slash.embedded.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#slash-language</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.basic</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>escaped-char</key>
        <dict>
            <key>match</key>
            <string>\\(?:x[\da-fA-F]{2}|.)</string>
            <key>name</key>
            <string>constant.character.escape.slash</string>
        </dict>
        <key>nest_curly_r</key>
        <dict>
            <key>begin</key>
            <string>\{</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.scope.slash</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_curly_r</string>
                </dict>
            </array>
        </dict>
        <key>slash-language</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>#</string>
                    <key>end</key>
                    <string>$</string>
                    <key>name</key>
                    <string>comment.line.slash</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>/\*</string>
                    <key>end</key>
                    <string>\*/</string>
                    <key>name</key>
                    <string>comment.block.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.class.slash</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.type.class.slash</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.extends.slash</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>entity.other.inherited-class.slash</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>^\s*(class)\s+([A-Z][A-Za-z0-9_]*)\s+(extends)\s+([A-Z][A-Za-z0-9_]*)</string>
                    <key>name</key>
                    <string>meta.class.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.def.slash</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.language.slash</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.punctuation.slash</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.method-name.slash</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>^\s*(def)\s+(self)(\.)([A-Za-z_][A-Za-z0-9_]*|\[\]=?|&lt;&lt;|&gt;&gt;|\+|-|\*\*|\*|/|%|==|!=|&lt;=&gt;|&lt;=|&lt;|&gt;=|&gt;|\^|&amp;|\||~)</string>
                    <key>name</key>
                    <string>meta.def.sing-self.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.def.slash</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>storage.ivar.slash</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.punctuation.slash</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.method-name.slash</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>^\s*(def)\s+(@@?[A-Za-z0-9_]+)(\.)([A-Za-z_][A-Za-z0-9_]*|\[\]=?|&lt;&lt;|&gt;&gt;|\+|-|\*\*|\*|/|%|==|!=|&lt;=&gt;|&lt;=|&lt;|&gt;=|&gt;|\^|&amp;|\||~)</string>
                    <key>name</key>
                    <string>meta.def.sing-icvar.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.def.slash</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>support.class.slash</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.punctuation.slash</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.method-name.slash</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>^\s*(def)\s+([A-Z][a-zA-Z0-9_]*)(\.)([A-Za-z_][A-Za-z0-9_]*|\[\]=?|&lt;&lt;|&gt;&gt;|\+|-|\*\*|\*|/|%|==|!=|&lt;=&gt;|&lt;=|&lt;|&gt;=|&gt;|\^|&amp;|\||~)</string>
                    <key>name</key>
                    <string>meta.def.sing-constant.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.def.slash</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.method-name.slash</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>^\s*(def)\s+([A-Za-z_][A-Za-z0-9_]*|\[\]=?|&lt;&lt;|&gt;&gt;|\+|-|\*\*|\*|/|%|==|!=|&lt;=&gt;|&lt;=|&lt;|&gt;=|&gt;|\^|&amp;|\||~)</string>
                    <key>name</key>
                    <string>meta.def.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(class|extends|def|if|elsif|else|unless|for|in|while|until|and|or|not|lambda|try|catch|return|next|last|throw)\b</string>
                    <key>name</key>
                    <string>keyword.language.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\bself\b</string>
                    <key>name</key>
                    <string>variable.language.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(nil|true|false)\b</string>
                    <key>name</key>
                    <string>constant.language.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>-?[0-9]+e[+-]?[0-9]+</string>
                    <key>name</key>
                    <string>constant.integer-with-exponent.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>-?[0-9]+(\.[0-9]+)(e[+-]?[0-9]+)?</string>
                    <key>name</key>
                    <string>constant.float.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>-?[0-9]+</string>
                    <key>name</key>
                    <string>constant.integer.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b([A-Z][a-zA-Z0-9_]*)</string>
                    <key>name</key>
                    <string>support.class.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.function-call</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>([a-z_][a-zA-Z0-9_]*)\s*(?:\()</string>
                    <key>name</key>
                    <string>method-call.implicit-self.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.function-call</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=[.:])([a-z_][a-zA-Z0-9_]*)</string>
                    <key>name</key>
                    <string>method-call.explicit-self.slash</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[a-z_][a-zA-Z_0-9]*</string>
                    <key>name</key>
                    <string>variable.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>storage.ivar.slash</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>@[a-zA-Z_0-9]+</string>
                    <key>name</key>
                    <string>variable.ivar.slash</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>storage.cvar.slash</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>@@[a-zA-Z_0-9]+</string>
                    <key>name</key>
                    <string>variable.cvar.slash</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>end</key>
                    <string>"</string>
                    <key>name</key>
                    <string>string.double-quoted.slash</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#escaped-char</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>'[A-Za-z0-9_]+</string>
                    <key>name</key>
                    <string>string.single-quoted.slash</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>%r\{</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.slash</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\}[a-z]*</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.slash</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.regexp.slash</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#nest_curly_r</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>&lt;&lt;=|&gt;&gt;=|&lt;&lt;|&gt;&gt;|==|!=|=&gt;|=|&lt;=&gt;|&lt;=|&lt;|&gt;=|&gt;|\+\+|--|\+=|-=|\*\*=|\*=|/=|%=|\+|-|\*\*|\*|/|%|\^=|&amp;=|&amp;&amp;=|\|=|\|\|=|\^|~|&amp;|&amp;&amp;|\||\|\||!|\.\.\.|\.\.|\.|::|:|λ|\\</string>
                    <key>name</key>
                    <string>keyword.punctuation.language.slash</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.slash</string>
    <key>uuid</key>
    <string>B7C52060-3813-47D8-8C8C-F00ADF6256C4</string>
</dict>
</plist>
